version: "3.4"
services:
  api:
    container_name: tarot-gpt-aiogram_bot
    image: tarot-gpt-aiogram
    build:
      context: .
    ports:
      - "8000:8000"
    command: "bot"
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
      - .:/opt/tarot-gpt-bot