name: Deploy
 
on:
    workflow_dispatch
jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            -   run: ls -la
            -   uses: actions/checkout@master
 
            -   run: sudo apt-get install rsync
            
            -   name: Deploy theme on server
                id: deploy_theme
                uses: Pendect/action-rsyncer@v1.1.0
                env:
                    DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
                with:
                    flags: '-avc --delete'
                    src: '/'
                    dest: 'root@"${{secrets.SERVER_IP}}":/root/tarot-gpt-bot'
            -   name: Test SSH Command
                uses: nekiro/ssh-job@main
                with:
                    host: ${{ secrets.HOST }}
                    key: ${{ secrets.KEY }}
                    user: ${{ secrets.USER }}
                    command: |
                        ls
                        mkdir dir
            -   name: Display status from deploy
                run: echo "${{ steps.deploy.outputs.status }}"
